[versions]
ksp = "2.0.21-1.0.27"

[libraries]
ksp-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
pf4j = { group = "org.pf4j", name = "pf4j", version = "3.12.1" }

[plugins]
gradle-publish = { id = "com.gradle.plugin-publish", version = "1.3.0" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version = "5.5.0" }
